#!/bin/sh

# install gvim by compiling from source.
# From https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source

cd ~

sudo apt-get install checkinstall -y
sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev mercurial -y

sudo apt-get remove vim vim-runtime gvim -y
sudo apt-get remove vim-tiny vim-common vim-gui-common -y

cd ~
hg clone https://code.google.com/p/vim/
cd vim
./configure --with-features=huge \
            --enable-rubyinterp \
            --enable-pythoninterp \
            --with-python-config-dir=/usr/lib/python2.7-config \
            --enable-perlinterp \
            --enable-luainterp \
            --enable-gui=gtk2 --enable-cscope --prefix=/usr
make VIMRUNTIMEDIR=/usr/share/vim/vim74
sudo checkinstall

sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
sudo update-alternatives --set editor /usr/bin/vim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
sudo update-alternatives --set vi /usr/bin/vim

vim --version

# setup vimrc and point to repo vimrc
mkdir .vim
# pull down vimrc
git clone https://github.com/ctasims/.vim ~/vimrc-repo
#symlink to vimrc
ln -s ~/vimrc-repo/vimrc ~/.vimrc

# setup Vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# install vundle plugins
vim +PluginInstall +qall

# install dev tools and CMake for YCM
sudo apt-get install build-essential cmake python-dev -y

# compile YCM
cd ~/.vim/bundle/YouCompleteMe
./install.sh --clang-completer


